### PR TITLE
Don't modify Field instances during requests

### PR DESCRIPTION
**Pull request by dotsbb**
Unit test for https://github.com/django-tastypie/django-tastypie/issues/1415

Failed test for the first commit https://travis-ci.org/django-tastypie/django-tastypie/builds/103124056

Updating related resource using PATCH method causing following error:

```bash
======================================================================
ERROR: test_one_to_one_two_patches (related_resource.tests.OneToOneTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/alex/www/django-tastypie/tests/related_resource/tests.py", line 1154, in test_one_to_one_two_patches
    resp = self.resource.patch_detail(request, pk=tag2.pk)
  File "/var/alex/www/django-tastypie/tests/../tastypie/resources.py", line 1661, in patch_detail
    self.update_in_place(request, bundle, deserialized)
  File "/var/alex/www/django-tastypie/tests/../tastypie/resources.py", line 1687, in update_in_place
    return self.obj_update(bundle=original_bundle, **kwargs)
  File "/var/alex/www/django-tastypie/tests/../tastypie/resources.py", line 2214, in obj_update
    return self.save(bundle, skip_errors=skip_errors)
  File "/var/alex/www/django-tastypie/tests/../tastypie/resources.py", line 2300, in save
    self.save_related(bundle)
  File "/var/alex/www/django-tastypie/tests/../tastypie/resources.py", line 2360, in save_related
    setattr(related_obj, field_object.related_name, bundle.obj)
AttributeError: 'NoneType' object has no attribute 'tag'

----------------------------------------------------------------------
Ran 32 tests in 1.342s

FAILED (errors=1)
```

### CODE REVIEW

**Comment by SeanHayes** [comment]
Not sure what this is for, #1415 refers to a few places where we set attributes on tastypie ApiField instances, which is bad practice.

**Comment by dotsbb** [comment]
@SeanHayes It's bad practice and what is more important:
 with this https://github.com/django-tastypie/django-tastypie/pull/1378 You introduced a new bug. 
I've provided [a unit test](https://github.com/stxnext/django-tastypie/commit/a4d38be71b0b03e5c99e90b95f0c8bf38891f3f8#diff-626dacabe704c842884f31139e1cf342R1139) which proves that bug exists..
Feel free to ask any questions.

**Comment by SeanHayes** [comment]
For future reference: I tried the testcase locally without any application code changes, and it passed.

**Comment by dotsbb** [comment]
@SeanHayes yes, It was fixed in another PR https://github.com/django-tastypie/django-tastypie/pull/1436

**Comment by SeanHayes** [comment]
Ahh, right. Didn't see the link to that PR, thanks.
