### ISSUE TITLE
ImportError: cannot import name migrations

### ISSUE THREAD

**Issue by ErikEvenson** [django-tastypie/django-tastypie#1228]
I get the following stack trace when upgrading from 0.11.1 to 0.12.0 and running `python manage.py migrate`.  I am running Django 1.6.7 and South 0.8.4.  It looks like tastypie is looking for a Django 1.7 migrations module.  I'm assuming tastypie 0.12.0 is compatible with Django 1.6.7 pre-Django migration code.  Perhaps the import should be conditional?

Thanks

Stacktrace:

```
Migrating development database...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/base.py", line 229, in calculate_dependencies
    migration.calculate_dependencies()
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/base.py", line 363, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/base.py", line 343, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/base.py", line 315, in migration_class
    return self.migration().Migration
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/base.py", line 304, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'tastypie:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/vagrant/.virtualenvs/VBEZ/lib/python2.7/site-packages/tastypie/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

**Comment by waqmax** [comment]
After facing a similar problem, upgrading South from 0.7.5 to 1.2 has solved the problem for me. I'm using Django 1.6.0 btw.
