### ISSUE TITLE
Django 3.0: ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by kevin-olbrich** [django-tastypie/django-tastypie#1602]
File "/XXX/venv/lib/python3.7/site-packages/tastypie/models.py", line 9, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/XXX/venv/lib/python3.7/site-packages/django/utils/encoding.py)

**Comment by kevin-olbrich** [comment]
File "/XXX/venv/lib/python3.7/site-packages/tastypie/utils/dict.py", line 1, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/XXX/venv/lib/python3.7/site-packages/django/utils/__init__.py)

**Comment by kevin-olbrich** [comment]
It's time to drop Py2 support.

**Comment by georgedorn** [comment]
We will likely address this with a compatibility shim in the next release, and drop support for python2 in a larger refactor around the time EOL arrives.

Work on Django 3.0 compatibility has not yet begun, though I'm happy to take pull requests to speed up the process.

On December 4, 2019 11:49:32 AM PST, Kevin Olbrich <notifications@github.com> wrote:
>It's time to drop Py2 support.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/django-tastypie/django-tastypie/issues/1602#issuecomment-561810890

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by georgedorn** [comment]
Fixed in v0.14.3
